NumPy is a fundamental package for data analysis in Python as the majority of other packages in the Python data eco-system build on it. Subsequently, it makes sense for us to have an understanding of what NumPy can help us with and its general principles.

In the following article, we’ll take a look at arrays in Python – which essentially take the ‘lists’ data type to a new level. We’ll have powerful new methods, random number generation and a way of storing data in grid-like structures, not just lists like we have seen.

In [1]:
import numpy as np


## Creating a NumPy array


In [2]:
# Three lists, one for GK heights, one for GK weigghts, one for names

GKNames = ["Kaller","Fradeel","Hayward","Honeyman"]
GKHeights = [184,188,191,193]
GKWeights = [81,85,103,99]

In [3]:
#create an array of names
nameArray = np.array(GKNames)
print(nameArray)

['Kaller' 'Fradeel' 'Hayward' 'Honeyman']


In [5]:
#Create a matrix of all three lists, start with a list of lists
GKMatrix = [GKNames,GKHeights,GKWeights]
arrayGKMatrix = np.array(GKMatrix)
print(arrayGKMatrix)

[['Kaller' 'Fradeel' 'Hayward' 'Honeyman']
 ['184' '188' '191' '193']
 ['81' '85' '103' '99']]


Aside from creating arrays from lists we already have, numpy can create them with its own methods:



In [7]:
#With 'arange', we can create arrays just like we created lists with 'range'
print(np.arange(0,20))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
# Create blank array with zeros

np.zeros((3,20)) # 3 rows , 20 columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [10]:
#Creates random numbers around a standard distribution from 0
print(np.random.randn(3,3))

[[ 0.10232264 -0.24356104  0.54797226]
 [ 0.28167159  1.17209239 -0.80649178]
 [-1.48268758 -0.99971271 -0.91989008]]


In [11]:
#Creates random numbers between two numbers that we give it
#The third argument gives us the shape of the array
print(np.random.randint(1,100,(3,3)))  # create a 3x3 array with values between 1 and 100

[[47 14 44]
 [37 91 43]
 [58  2 29]]


## Array Methods

Not only does NumPy give us a good way to store our data, it also gives us some great tools to simplify working with it.

Let’s find the tallest goalkeeper from our earlier examples with array methods.

In [14]:
arrayGKNames = nameArray
arrayGKHeights = np.array(GKHeights)
arrayGKWeights = np.array(GKWeights)

In [17]:
#What is the largest height, max()?
arrayGKHeights.max()
#name of this player
arrayGKNames[arrayGKHeights.argmax()]


'Honeyman'